import { describe, expect, it } from "vitest";
import {
	renderSession,
	renderFullDoc,
	renderOverviewBlock,
	renderSummaryBlock,
	renderDialogBlock,
	renderDialogTail,
	renderToolsBlock,
	renderWarningsBlock,
	cleanTurns,
	buildDialogItems,
	cleanMessageText,
	FOLDABLE_HEADING_PREFIXES,
	SECTION_KIND,
} from "../../src/core/session-sync/engine/render";
import type { NormalizedSession } from "../../src/core/session-sync/engine/types";

function session(over: Partial<NormalizedSession> = {}): NormalizedSession {
	return {
		source: "codex",
		sessionId: "p1",
		createdAt: "2026-05-01T10:00:00Z",
		updatedAt: "2026-05-01T11:00:00Z",
		cwd: "/x/proj",
		messages: [
			{ role: "user", text: "fix the login bug", timestamp: "t1" },
			{ role: "assistant", text: "Done.\n\n```js\nok()\n```", timestamp: "t2" },
		],
		toolActivities: [],
		parseWarnings: [],
		...over,
	};
}

describe("renderSession readability", () => {
	it("emits no body H1 (the doc title is the heading)", () => {
		const md = renderSession(session());
		expect(md.startsWith("## 📋 概览")).toBe(true);
		expect(md).not.toMatch(/^# /m);
	});

	it("user turns are blockquotes (🧑), assistant turns are plain blocks (🤖)", () => {
		const md = renderSession(session());
		expect(md).toContain("> 🧑");
		expect(md).toContain("> fix the login bug");
		expect(md).toContain("🤖");
		expect(md).toContain("```js"); // assistant code renders natively (not quoted)
		expect(md).not.toContain("> ```js");
	});

	it("结论 is a muted 问→答 callout (blockquote, no heading)", () => {
		const md = renderSession(session());
		expect(md).not.toContain("## 🎯 结论"); // de-emphasized: not a heading
		expect(md).toContain("> 🎯 **问** fix the login bug");
		expect(md).toContain("> **答** Done.");
	});

	it("tool + warning sections use foldable heading prefixes", () => {
		const md = renderSession(
			session({
				toolActivities: [{ kind: "shell", summary: "`npm test` → exit 0", timestamp: "t", status: "success" }],
				parseWarnings: ["ignored trailing partial json line"],
			}),
		);
		expect(md).toContain("## 🔧 工具调用 (1)");
		expect(md).toContain("## ⚠️ 解析警告");
		// every foldable section heading must match a prefix the writer folds
		for (const prefix of FOLDABLE_HEADING_PREFIXES) {
			expect(md).toContain(`## ${prefix}`);
		}
		expect(md).toContain("- ✅ **shell** `npm test` → exit 0");
	});

	it("flags failed tools in the conclusion", () => {
		const md = renderSession(
			session({ toolActivities: [{ kind: "shell", summary: "`x` → exit 1", timestamp: "t", status: "failure" }] }),
		);
		expect(md).toContain("⚠️ 有 1 个工具调用失败");
		expect(md).toContain("- ❌ **shell**");
	});

	it("strips injected noise and skips emptied turns", () => {
		const md = renderSession(
			session({
				messages: [
					{ role: "user", text: "<system-reminder>CLAUDE.md ...</system-reminder>", timestamp: "t1" }, // → empty, skipped
					{ role: "user", text: "real question\n<system-reminder>noise</system-reminder>", timestamp: "t2" },
					{ role: "assistant", text: "ok", timestamp: "t3" },
				],
			}),
		);
		expect(md).not.toContain("system-reminder");
		expect(md).toContain("> real question");
		// the reminder-only user turn is dropped, so only one 🧑 user block
		expect(md.match(/^> 🧑$/gm)?.length).toBe(1);
	});

	it("strips <local-command-caveat> + <command-*> wrappers, keeps the real message", () => {
		const md = renderSession(
			session({
				messages: [
					{ role: "user", text: "<task-notification>\n<task-id>bt9</task-id>\n<status>completed</status>\n</task-notification>", timestamp: "t0" }, // → empty, skipped
					{
						role: "user",
						text: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond.</local-command-caveat>\n<command-name>/deploy</command-name>\n重新梳理当前的价格体系",
						timestamp: "t1",
					},
					{ role: "assistant", text: "好的", timestamp: "t2" },
				],
			}),
		);
		expect(md).not.toContain("Caveat:");
		expect(md).not.toContain("local-command");
		expect(md).not.toContain("command-name");
		expect(md).not.toContain("task-notification");
		expect(md).toContain("重新梳理当前的价格体系");
	});

	it("inlines sub-agent entries as asset links (no standalone section) with rollup", () => {
		const md = renderSession(session(), {
			subAgents: [
				{ assetPath: "assets/session-sync/codex-d1.md", title: 'fix the "login" bug', role: "worker", nickname: "Ada", toolCount: 5, failedToolCount: 1, createdAt: "2026-05-01T10:30:00Z" },
				{ assetPath: "assets/session-sync/codex-d2.md", title: "b", role: "worker", nickname: "Ada", toolCount: 3, failedToolCount: 0, createdAt: "2026-05-01T10:31:00Z" },
			],
		});
		expect(md).not.toContain("## 🧩 子代理"); // no standalone section
		expect(md).toContain('> 🧩 **子代理** [worker · Ada — fix the "login" bug](assets/session-sync/codex-d1.md)');
		expect(md).toContain("worker · Ada (2)"); // de-duped label
		expect(md).toContain("| 子代理 | 2（工具 8，失败 1） |"); // overview rollup kept
	});

	it("places a sub-agent entry between the turns it was triggered between (by createdAt)", () => {
		const md = renderSession(
			session({
				messages: [
					{ role: "user", text: "do A", timestamp: "2026-05-01T10:00:00Z" },
					{ role: "assistant", text: "spawning a worker", timestamp: "2026-05-01T10:00:10Z" },
					{ role: "assistant", text: "worker finished", timestamp: "2026-05-01T10:05:00Z" },
				],
			}),
			{ subAgents: [{ assetPath: "assets/session-sync/codex-w1.md", title: "the worker", role: "worker", createdAt: "2026-05-01T10:00:30Z" }] },
		);
		const convo = md.slice(md.indexOf("## 💬 对话"));
		const iSpawn = convo.indexOf("spawning a worker");
		const iSub = convo.indexOf("🧩 **子代理**");
		const iDone = convo.indexOf("worker finished");
		expect(iSpawn).toBeGreaterThan(-1);
		expect(iSub).toBeGreaterThan(iSpawn); // after the spawning turn
		expect(iDone).toBeGreaterThan(iSub); // before the finished turn
	});

	it("omits sub-agent markers when there are none", () => {
		const md = renderSession(session());
		expect(md).not.toContain("🧩");
	});

	it("inlines a cross-tool invocation note (codex→claude), ignoring noise", () => {
		const md = renderSession(
			session({
				toolActivities: [
					{ kind: "shell", summary: "`which claude` → exit 0", timestamp: "2026-05-01T10:00:01Z", status: "success" },
					{ kind: "shell", summary: "`claude -p \"do the work\"` → exit 0", timestamp: "2026-05-01T10:00:02Z", status: "success" },
					{ kind: "shell", summary: "`grep claude-code/src` → exit 0", timestamp: "2026-05-01T10:00:03Z", status: "success" },
				],
			}),
		);
		expect(md).toContain("↗ **调用 claude**");
		expect(md).toContain('claude -p "do the work"');
		expect((md.match(/↗ \*\*调用/g) || []).length).toBe(1); // which/path noise excluded
	});
});

describe("section / tail renderers (incremental)", () => {
	it("renderFullDoc is the same function as renderSession (backward-compat alias)", () => {
		expect(renderFullDoc).toBe(renderSession);
	});

	it("SECTION_KIND values match the attr namespace the reconciler will set", () => {
		expect(SECTION_KIND.overview).toBe("overview");
		expect(SECTION_KIND.summary).toBe("summary");
		expect(SECTION_KIND.dialog).toBe("dialog");
		expect(SECTION_KIND.tools).toBe("tools");
		expect(SECTION_KIND.warnings).toBe("warnings");
	});

	it("renderOverviewBlock returns just the overview, no trailing blank", () => {
		const md = renderOverviewBlock(session(), {}, []);
		expect(md.startsWith("## 📋 概览")).toBe(true);
		expect(md).toContain("| 来源 | codex |");
		expect(md.endsWith("\n")).toBe(false); // trailing blank trimmed
		expect(md).not.toContain("## 💬"); // doesn't bleed into next section
	});

	it("renderSummaryBlock returns the muted 问→答 callout (no heading)", () => {
		const md = renderSummaryBlock(session(), cleanTurns(session()));
		expect(md).toContain("> 🎯 **问** fix the login bug");
		expect(md).toContain("> **答** Done.");
		expect(md).not.toContain("##");
	});

	it("renderSummaryBlock returns '' for a session with no turns and no failures", () => {
		const empty = session({ messages: [], toolActivities: [], parseWarnings: [] });
		expect(renderSummaryBlock(empty, cleanTurns(empty))).toBe("");
	});

	it("renderToolsBlock returns '' when there are no tool activities", () => {
		expect(renderToolsBlock(session())).toBe("");
	});

	it("renderWarningsBlock returns '' when there are no parse warnings", () => {
		expect(renderWarningsBlock(session())).toBe("");
	});

	it("renderDialogBlock embeds the heading + content for the first emission", () => {
		const s = session();
		const items = buildDialogItems(s, cleanTurns(s), []);
		const md = renderDialogBlock(items);
		expect(md.startsWith("## 💬 对话")).toBe(true);
		expect(md).toContain("> 🧑");
		expect(md).toContain("> fix the login bug");
	});

	it("renderDialogTail returns '' for empty items", () => {
		expect(renderDialogTail([], null)).toBe("");
	});

	it("renderDialogTail emits role banner when prevRole is null", () => {
		const md = renderDialogTail(
			[{ ts: "t", kind: "msg", role: "assistant", text: "Hi" }],
			null,
		);
		expect(md).toContain("🤖");
		expect(md).toContain("Hi");
		// No heading (tail is body-only).
		expect(md).not.toContain("## 💬");
	});

	it("renderDialogTail omits the role banner when prevRole already matches (continuation)", () => {
		const md = renderDialogTail(
			[{ ts: "t", kind: "msg", role: "assistant", text: "follow-up" }],
			"assistant",
		);
		expect(md).not.toContain("🤖");
		expect(md.trim()).toBe("follow-up");
	});

	it("renderDialogTail emits a new role banner when prevRole differs", () => {
		const md = renderDialogTail(
			[{ ts: "t", kind: "msg", role: "user", text: "next question" }],
			"assistant",
		);
		expect(md).toContain("> 🧑");
		expect(md).toContain("> next question");
	});
});

describe("cleanMessageText", () => {
	it("removes wrapper tags + caveats, collapses blank lines", () => {
		expect(cleanMessageText("a\n\n\n\nb")).toBe("a\n\nb");
		expect(cleanMessageText("<command-name>/x</command-name>keep")).toBe("keep");
		expect(cleanMessageText("Caveat: local thing\nkeep")).toBe("keep");
		expect(cleanMessageText("<system-reminder>x</system-reminder>")).toBe("");
	});
});
